######################
### Route Employ ####
######################

### Login Employ
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "budi",
    "password": "update"
}

### Testing Dashboard Employ
GET http://localhost:5000/dashboard


### View Data Salary By Month
GET http://localhost:5000/salary_data/month/juni

### View Data Salary By Year
GET http://localhost:5000/salary_data/year/2023

### Change Password Employ (Self)
PATCH  http://localhost:5000/change_password
Content-Type: application/json

{
    "password" : "update",
    "confPassword" : "update"
}

### Logout User
DELETE   http://localhost:5000/logout