######################
#### Route Admin #####
######################

### Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "aldi",
    "password": "update"
} 

### Get Me
GET http://localhost:5000/me

### Logout User
DELETE   http://localhost:5000/logout



### === Change Password === ###

### Change Password Employ (Self)
PATCH  http://localhost:5000/change_password
Content-Type: application/json

{
    "password" : "update",
    "confPassword" : "update"
}

### Change Password Admin (All Employee Data)
PATCH  http://localhost:5000/employee_data/2/change_password
Content-Type: application/json

{
    "password":"budi",
    "confPassword":"budi"
}




#############################
####  Master Data Admin  ####
#############################

/////// Employee Data //////

### get All Employee Data
GET http://localhost:5000/employee_data


### get Single Employee Data by ID
GET http://localhost:5000/employee_data/id/2

### get Single Employee Data by NIK
GET http://localhost:5000/employee_data/nik/223344

### get Single Employee Data by NAME
GET http://localhost:5000/employee_data/name/budi

### Create Employee Data
POST http://localhost:5000/employee_data
Content-Type: application/json

{
    "nik": 223344,
    "employee_name": "Cecep",
    "username": "cecep",
    "password": "12345",
    "confPassword": "12345",
    "gender": "Male",
    "position": "Operator Produksi",
    "joining_date": "11-02-2023",
    "status": "Permanent employee",
    "photo": ,
    "access_rights": "employ"
}



### Update Employee Data
PATCH  http://localhost:5000/employee_data/2
Content-Type: application/json

{
    "nik": 223344,
    "employee_name": "Budi",
    "username": "budi",
    "gender": "Male",
    "position": "Operator Produksi",
    "joining_date": "11-02-2023",
    "status": "Permanent employee",
    "photo": ,
    "access_rights": "employ"
}

### Change Password Admin (All Employee Data)
PATCH  http://localhost:5000/employee_data/2/change_password
Content-Type: application/json

{
    "password":"budi",
    "confPassword":"budi"
}

### Change Password Employ (Self)
PATCH  http://localhost:5000/change_password
Content-Type: application/json

{
    "password" : "update",
    "confPassword" : "update"
}

### Delete Employee Data
DELETE   http://localhost:5000/employee_data/


/////// Position Data //////

### Get All Position Data
GET  http://localhost:5000/position_data

### Create Position Data
POST  http://localhost:5000/position_data
Content-Type: application/json

{
    "position_name" : "Operator Produksi",
    "basic_salary" : 2000,
    "transport_allowance" : 1000,
    "meal_allowance" : 500
}

### UPDATE Position Data
PATCH   http://localhost:5000/position_data/1
Content-Type: application/json

{
    "position_name" : "Kepala Bagian",
    "basic_salary" : 5000,
    "transport_allowance" : 2000,
    "meal_allowance" : 1000
}

### DELETE Position Data
DELETE    http://localhost:5000/position_data/2



#############################
###### Transaction Admin ######
#############################

/////// Attendance Data //////

### Get All Attendance Data
GET  http://localhost:5000/attendance_data

### Create Attendance Data
POST  http://localhost:5000/attendance_data
Content-Type: application/json

{
    "nik": "223344",
    "employee_name": "Budi",
    "position_name": "Operator Produksi",
    "gender": "Laki - Laki",
    "present": "9",
    "sickdays": "2",
    "absences": "1"
}

### UPDATE Attendance Data
PATCH  http://localhost:5000/attendance_data/update/11
Content-Type: application/json

{
    "present": "2",
    "sickdays": "2",
    "absences": "2"
}

### DELETE Attendance Data
DELETE http://localhost:5000/attendance_data/8


/////// Data Deduction //////

### Get All Data Deduction Salary
GET  http://localhost:5000/data_deduction

### Get Data Deduction Salary By ID
GET  http://localhost:5000/data_deduction/23

### Create Data Deduction
POST  http://localhost:5000/data_deduction
Content-Type: application/json

{
    "id" : 1 ,
    "deduction": "absences",
    "total_deduction": 2000
}

### UPDATE data deduction
PATCH  http://localhost:5000/data_deduction/update/3
Content-Type: application/json

{
    "deduction" : "updated 1",
    "total_deduction" : 9999
}

### DELETE Data Deduction
DELETE http://localhost:5000/data_deduction/3



/////// Data Salary //////

### get All Data Salary Employ
GET http://localhost:5000/employee_salary_data

### get Data Salary Employ By Name
GET http://localhost:5000/salary_data/name/Aldi Ramdani

### get All Data Salary Employ By Month
GET http://localhost:5000/employee_salary_data/month/Juni

### get All Data Salary Employ By Year
GET http://localhost:5000/employee_salary_data/year/2023

// NOTE: Data Month & Year (month & year) ditetapkan berdasarkan input Employee Attendance Data.



#############################
####### Report Admin #######
#############################

/////// Salary Report //////

### get All Data Salary Report
GET http://localhost:5000/Report/salary

### get All Data Salary Report By Name
GET http://localhost:5000/Report/salary/name/nana

### get All Data Salary Report By Month
GET http://localhost:5000/Report/salary/month/juli

### get All Data Salary Report By Year
GET http://localhost:5000/Report/salary/year/2023



/////// Attendance Report //////

GET http://localhost:5000/Report/attendance/month/maret

### get All Data Attendance Report By Year
GET http://localhost:5000/Report/attendance/year/2021



/////// Salary Slip //////

### get Salary Slip By Name
GET http://localhost:5000/Report/salary_slip/name/caca

### get Salary Slip By Month
GET http://localhost:5000/Report/salary_slip/month/maret

### get Salary Slip By Year
GET http://localhost:5000/Report/salary_slip/year/2022