export const GET_SALARY_DATA_SUCCESS = 'GET_SALARY_DATA_SUCCESS';
export const GET_SALARY_DATA_FAILURE = 'GET_SALARY_DATA_FAILURE';
export const DELETE_SALARY_DATA_SUCCESS = 'DELETE_SALARY_DATA_SUCCESS';
export const DELETE_SALARY_DATA_FAILURE = 'DELETE_SALARY_DATA_FAILURE';
