export const GET_DATA_DEDUCTION_SUCCESS = 'GET_DATA_DEDUCTION_SUCCESS';
export const GET_DATA_DEDUCTION_FAILURE = 'GET_DATA_DEDUCTION_FAILURE';
export const CREATE_DATA_DEDUCTION_SUCCESS = 'CREATE_DATA_DEDUCTION_SUCCESS';
export const CREATE_DATA_DEDUCTION_FAILURE = 'CREATE_DATA_DEDUCTION_FAILURE';
export const UPDATE_DATA_DEDUCTION_SUCCESS = 'UPDATE_DATA_DEDUCTION_SUCCESS';
export const UPDATE_DATA_DEDUCTION_FAILURE = 'UPDATE_DATA_DEDUCTION_FAILURE';
export const DELETE_DATA_DEDUCTION_SUCCESS = 'DELETE_DATA_DEDUCTION_SUCCESS';
export const DELETE_DATA_DEDUCTION_FAILURE = 'DELETE_DATA_DEDUCTION_FAILURE';
